<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <DotnetCliToolTargetFramework>net9.0</DotnetCliToolTargetFramework>
    <UserSecretsId>34da1f7e-a590-4675-80ca-3cf90e9f9742</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\EggsAndToast.Data\EggsAndToast.Data.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="IntelliTect.Coalesce.Vue" Version="$(CoalesceVersion)" />
  </ItemGroup>

  <ItemGroup>
    <DotNetCliToolReference Include="IntelliTect.Coalesce.Tools" Version="$(CoalesceVersion)" />
  </ItemGroup>
</Project>
